#!/bin/sh
. "$(dirname "$0")/_/husky.sh"
 
yarn run post-merge

CHANGED_FILES="$(git diff-tree ORIG_HEAD HEAD -r --name-only --no-commit-id)"
EXIT_CODE="$(git diff --exit-code ORIG_HEAD HEAD package.json)"

if [$EXIT_CODE == 1]
echo "asdf"